server:
  port: 8888

spring:
  application:
    name: springcloud-zuul  # 应用的名称   多实例 名称必须保持一致

# 配置服务注册信息
eureka:
  client:
    service-url:
      #defaultZone: http://localhost:7001/eureka # eureka服务器的地址   单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版
  instance:
    instance-id: springcloud-zuul:8888  #设置访问的别名
    prefer-ip-address: true        #显示ip地址

#配置路由规则
zuul:
  #ignored-services: springcloud-dept # 忽略指定名称  只能从path映射路径访问
  #ignored-services: "*"  #忽略所有原来的名称
  routes:
    mydept:
      path: /mydept/**  # 映射路径
      service-id: springcloud-dept #对应具体服务名称
  prefix: /bj1901  # 前缀